### ISSUE TITLE
Only Like Subscribed Channels + Custom Timer/Custom Percentage not working

### ISSUE THREAD

**Issue by GiraffeCubed** [Taknok/youtube-auto-like#13]
## Expected Behavior
1.) With the Only Like Subscribed Channels option enabled, all watched videos from my subscribed channels should be automatically liked in the time that I alloted.

2.) I should be able to define a custom time/percentage that the video needs to be watched before an auto like is applied.

## Actual Behavior
1.) With the Only Like Subscribed Channels option enabled, no watched videos are ever auto liked, even those from subscribed channels.

2.) Custom time/percentage can be selected, but a value cannot be added in to the text box on the options page.

## Steps to Reproduce the Problem
1.) Enable Only Like Subscribed Channels option and watch a video from one of your subscribed channels.

2.) Enable custom time/percentage and notice that you cannot change the values of these options.

## Specifications

  - Version: 2.2.1
  - Platform: Windows 10 Pro x64
  - Subsystem: Firefox Quantum 63.0.1 (64-bit)

**Comment by Taknok** [comment]
Are you managing the addon from the [about:addons](about:addons) page ? I just check there and it seems that the css isn't properly applied in this page preventing to click in the box. I will check this, in the meantime I suggest you to use the popup window :/

**Comment by GiraffeCubed** [comment]
Yes, I was using about:addons
