### ISSUE TITLE
Don't like when I look videos on Watch Later

### ISSUE THREAD

**Issue by jbelbaz** [Taknok/youtube-auto-like#18]
## Expected Behavior

When I look videos on the Watch Later list the extention must be like the video

## Actual Behavior

When I look videos on the Watch Later list the extention didn't work

## Steps to Reproduce the Problem

  1.Go tu YT
  2.Put more than 10 video on Watch later
  3.Start to watch all videos, the extention didn't work :/

Config : 
Last version of stable firefox,  ✅- like all the video && ✅- like instantly

I'm french so all site and system is in french 

## Specifications

  - Version: 2.3.1
  - Platform: Windows 10 
  - Subsystem: Firefox

**Comment by Taknok** [comment]
Hi,

I also use the addon in my watch later playlist (and my system is also in french !) But I cannot reproduce the behavior. Do you have others addons working on youtube ? Have you tried with just the youtube-auto-like addon enabled ?
If you can reproduce the behavior on your side, could you provide more information (or a record) ? The like didn't happen at the third video each time, the 1 video was dislike and etc... what are the logs (ctrl + shift + i then console)?
Thanks

**Comment by Taknok** [comment]
Are you using the old youtube layout ?
