### ISSUE TITLE
Addon does not function on FF 58.0b7

### ISSUE THREAD

**Issue by DeadSix27** [Taknok/youtube-auto-like#2]
## Expected Behavior
Like videos

## Actual Behavior
Does not like videos

## Steps to Reproduce the Problem

  1. Download Firefox 58.0b7 (64-bit) (haven't tried any other browser)
  2. Install this addon
  3. Enable either setting, only subbed or all videos
  4. Visit youtube video, see nothing happen.

## Specifications

  - Version:  2.0.3
  - Platform: FF 58.0b7 (64-bit)  / Windows 10
  - Subsystem: ?

**Comment by Taknok** [comment]
Which version of youtube are you using ? The new "material" one ? or the old ?

**Comment by DeadSix27** [comment]
@Taknok Oh right, I forgot there are 2 styles.

I am using the old one (and will be for as long as I can :P)

I have not tested it on the new one

**Comment by Taknok** [comment]
Ok, I will check and update if there is a bug, maybe they changed a html class or so.

**Comment by Taknok** [comment]
Version updated : 2.0.4, is the bug fixed ?

**Comment by DeadSix27** [comment]
Yep fixed :)
