### ISSUE TITLE
Instant like works after reload only

### ISSUE THREAD

**Issue by kopach** [Taknok/youtube-auto-like#20]
## Expected Behaviour

Instant like to submit 👍 "like" just after I enter page with 

## Actual Behaviour

👍 "like" submitted only after page refresh

## Steps to Reproduce the Problem

  1. Select app options: "Like only videos from subscribed channels" + "Instant Like"
  1. Open any video from subscribed channel you haven't watched/liked before
  1. In new tab open "Liked Videos" page (from left sidebar)
  1. Video from step 2 isn't listed here
  1. go back to tab with opened video and refresh it
  1. go to tab with "Liked Videos" page - now video from step 2 is listed here

## Specifications

  - Version: 2.3.3
  - Platform: macOS Mojave 10.14.6

**Comment by Taknok** [comment]
Hi,

Thank you for your report ! I have few questions to find the origin of the issue. Whould you mind to answer it ?
- Which version of youtube are you using ? The "new" one named [material](https://cdn.vox-cdn.com/thumbor/KimIYyeHdCwNC-2EUJRcpcjktI8=/0x0:1494x840/1200x800/filters:focal(101x1:339x239)/cdn.vox-cdn.com/uploads/chorus_image/image/54575681/New_Dark_Theme.0.png) or the [old youtube](https://lh3.googleusercontent.com/wxzZ7bAenKdErX72b6EQJ8AMhAwAhBnuV6kbo6KpU-m9uLE-3xtqzZbGXzPyzf43GMBAQvuFYg=w640-h400-e365) ?
- This behaviors still is present with only youtube-auto-like enable (like in private navigation) ?
- Can you send here a display of [the console](https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Opening_the_Web_Console) (`cmd`+`⌥`+`K`) before and after the refresh ? This should look like this : 
![image](https://user-images.githubusercontent.com/12498020/70279457-d3049100-17b6-11ea-910d-e281e005fb1e.png)

**Comment by kopach** [comment]
hi @Taknok 

1. material one
2. yes
3. 
```
auto like injected content.js:15:10
material youtube detected content.js:25:12
yt-autolike start liker-material.js:257:11
uncaught exception: Object
MouseEvent.mozPressure is deprecated. Use PointerEvent.pressure instead. desktop_polymer_v2.js:1951:73
got buttons liker-material.js:67:13
not liked check 1 liker-material.js:274:14
yt-autolike start liker-material.js:257:11
got buttons liker-material.js:67:13
liked liker-material.js:299:15
```

<img width="483" alt="image" src="https://user-images.githubusercontent.com/8749624/70281062-478cff00-17ba-11ea-837f-b637da739884.png">


**Additional Info**
Was able to identify issue more precisely. This is reproducible when navigating to video from YouTube's home page, but not reproducible when I open link with target video directly

**Comment by Taknok** [comment]
Thank you for the information ! I will look on it this week end.

**Comment by Taknok** [comment]
Hi,

I pushed some modifications on this repo. Could you tell me if it solve the issue ? 
Steps:
1. Download the [zip of the master banch](https://github.com/Taknok/youtube-auto-like/archive/master.zip).
2. Unzip `master.zip`
3. Disable youtube-auto-like in `about:addons`
4. Load the file `master/app/manifest.json` as [temporary add-on](https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/) (Open `about:debugging` > This firefox > Load temp
5. Try it and tell me the result + console log

Thank you for all you time spent helping me improve the plugin !

**Comment by kopach** [comment]
Hi @Taknok. I can confirm, add-on from `master` doesn't have described issue any more. Thank you. Hope to see this fix released soon.

**Comment by Taknok** [comment]
Hi. Thank you for your feedback ! The update should be published soon.
