### ISSUE TITLE
Feature: whichever comes first between percentage and minutes

### ISSUE THREAD

**Issue by alexandre-pennetier** [Taknok/youtube-auto-like#23]
It's more of a feature request.

I'd like to auto like if either the percentage or the minutes have been reached.

For example, if I set 50% or 5 minutes : 
- For a video of 5 minutes, I won't have to watch the whole video to leave a like, 
- If the video lasts 30 minutes, I'll consider that if I watched it for at least 5 minutes (rather than 15), it's worth a like.

**Comment by Taknok** [comment]
Done in commit c40028df72fce62ba6015a848d1a9b037e8a6b45
