### ISSUE TITLE
V3.2.0+ does not work. 

### ISSUE THREAD

**Issue by velonici** [Taknok/youtube-auto-like#26]
## Expected Behavior
To auto like a youtube video from a subscribed creator.

## Actual Behavior
Does not auto like the video.

## Steps to Reproduce the Problem

  1. Go to video and observe that it is not working.
  1. Downgrading to v3.1.0 works again. 
  1.

## Specifications

  - Version: 3.2.1 (Started in 3.2.0)
  - Platform: Firefox V78.0.1 64bit on Windows 10
  - Subsystem:

**Comment by velonici** [comment]
And of course I figure it out 5min after posting this. Turns out the "Use list" was checked at some point to use a whitelist. Since I never set one up thats why it didnt work. Reinstalling 3.2.1 and unchecking that box fixed it.

**Comment by Taknok** [comment]
The issue is triggered by using a list + white list when the list is empty. This is a normal behavior: nothing is whitelisted so nothing is liked. I will published and update `3.2.2` which disable the list of user having an empty list.
