### ISSUE TITLE
Change from Instant Like doesnt work.

### ISSUE THREAD

**Issue by Cyric313** [Taknok/youtube-auto-like#27]
## Expected Behavior
changing when to like a video.

## Actual Behavior
Resets to instant like when opening next video.

## Specifications

  - Version: Last version on Firefox Store.
  - Platform: Wndows 10
  - Subsystem: Firefox

**Comment by Taknok** [comment]
Thank you for the report !
Version 3.2.3 should fix the issue. Tell me if it solve your issue.

**Comment by Taknok** [comment]
No more report, 3.2.3 have fixed the issue.
