### ISSUE TITLE
Sometimes refuses to like

### ISSUE THREAD

**Issue by UltraBlackLinux** [Taknok/youtube-auto-like#29]
## Expected Behavior

It should like every time

## Actual Behavior

Sometimes, it just kinda shuts down and doesnt like at all.

## Steps to Reproduce the Problem

Cant really tell

## Specifications

  - Version: 3.2.3
  - Platform: Linux

**Comment by Flavio514** [comment]
Experienced this today but my Internet went down due to a power outage so it might be related in an unknown way to me.

**Comment by Taknok** [comment]
Bug still present ?

**Comment by UltraBlackLinux** [comment]
@Taknok 
Unsure, I don't have this problem lately - I will reopen this, when the bug is present again
