### ISSUE TITLE
Notice: Chrome Extension removed due malware alert

### ISSUE THREAD

**Issue by StephanSteinert** [Taknok/youtube-auto-like#30]
## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by ZachTheDev** [comment]
@Taknok Are you republishing it? I tried to download the GitHub and running it locally, but there were errors and the options weren't saving.

**Comment by Taknok** [comment]
I'm not the owner of the chrome version. Austencm is the owner and the publisher for chrome : https://github.com/austencm/youtube-auto-like

**Comment by ZachTheDev** [comment]
@Taknok Had no idea, thanks for directing me!
