### ISSUE TITLE
[Feature request] Auto dislike

### ISSUE THREAD

**Issue by leodoi3** [Taknok/youtube-auto-like#31]
Can you make a auto-dislike version that has support for whitelists?

**Comment by Taknok** [comment]
This can be done by changing 2 lines in the code. I let you fork this repo and do this, because I do not want to created an auto dislike module.

**Comment by leodoi3** [comment]
I'll give it a shot. Could you let me know which lines I need to change?

**Comment by Taknok** [comment]
This [line](https://github.com/Taknok/youtube-auto-like/blob/22834f5c85e5b2dc495df1a1d775bd2ba30dcee6/app/scripts/modules/liker-material.js#L319).
