### ISSUE TITLE
Videos get liked based on the percent progress of pre-video advertisements

### ISSUE THREAD

**Issue by WolfIcefang** [Taknok/youtube-auto-like#32]
## Expected Behavior
I have YouTube Auto Like set to like the video after 50% watch time.

## Actual Behavior
If an advertisement plays before the video, the video will be liked at the 50% mark of the advertisement's runtime. Here is an example of the bug in action: https://open.lbry.com/YouTube-auto-like-bug:f?r=GSQAMBCjpx5BhjLngHqMsQLc5PUpAYvR

## Steps to Reproduce the Problem

  1. Turn off all ad blockers
  2. Find a video with an advertisement before the start.
  3. Play the advertisement, and see the video get liked at the 50% mark.

## Specifications

  - Version: 3.2.3 (Last Updated February 15, 2021)
  - Platform: Firefox Browser version 86.0 (64-bit)
  - Subsystem: Windows 10? (I'm not exactly sure what "subsystem" means.)

**Comment by Taknok** [comment]
Thank you for the feedbacks !
Tell me if issue is resolved with 3.2.4 release :)

**Comment by WolfIcefang** [comment]
I no longer have the issue with version 3.2.4. Thank you!
