### ISSUE TITLE
[Feature Request] hide the "Added to liked videos" popup

### ISSUE THREAD

**Issue by platinorum** [Taknok/youtube-auto-like#36]
It would be nice to have an option to hide the "Added to liked videos" popup, when a video was liked by the extension.

Thx for your great extension btw :)

**Comment by Taknok** [comment]
Unfortunately, all the popup notification has the same tag and CSS rules. Thus the removal cannot be done with simple CSS rules. This would need to get all string in all languages to remove the popup, which is not effective.
The more effective way would be to remove the popup trigger from the JS. Unfortunately (again) I have not the time to reverse the minified JS of YouTube at each change (~once a month).

That said, I will gladly accept any PR adding this functionality.
