### ISSUE TITLE
[Feature Request] Like all videos in a playlist

### ISSUE THREAD

**Issue by nclm** [Taknok/youtube-auto-like#37]
I’ve been looking for a solution to auto like all the videos contained in a playlist. This add-on seems to be the best contender to have this feature, so if it’s feasible, it would be nice to consider this function :)

**Comment by Taknok** [comment]
This is not the purpose of this add-on, thus it will not be implemented in this code. Sorry. **BUT** there is multiples ways to do it quickly (less than 30min of dev). One crappy would be to clone this code and get the "next button" after the like function is called and click on it. A second proper would be to use the [youtube api](https://developers.google.com/youtube) and iterate over elements in the playlist and like them trough youtube api.

**Comment by nclm** [comment]
Thanks for the reply. I will look into other solutions. I’m not a developer, so making this would take me a lot more than “30 minutes of dev”.

The way I was seeing it and that wasn’t I think totally off the scope of the add-on, was that sometimes you can subscribe to someone else’s playlist and want to like everything that is added to it, for instance when a creator you subscribe to has several series or programmes, each in their playlist, and you might want to like all the episodes of one of these but not of the others. And in that way, I feel it is close to what the add-on is about, just with more granularity of not liking “all the videos” but “all the videos of a series”.

**Comment by Taknok** [comment]
Ho, do you mean to add a filter to like only the "selected" video ? A "selected" video is a video that is in a playlist. Thus, if a creator post a video that is not in the category/playlist, it is not liked.

**Comment by nclm** [comment]
Yes, I think so, like if you go to https://www.youtube.com/c/timhunkin1/playlists or to https://www.youtube.com/user/crashcourse/playlists or to https://www.youtube.com/channel/UCh5JF-qt2ZXg8acejcJ15Xw/playlists, the creators have put each of their video series into different playlists. Maybe you are actually only interested in one or a few of them, and that’s the one you’d want to like.

**Comment by Taknok** [comment]
I just look to youtube documentation and to check if a video is in a specified playlist required an Youtube Data Api Token. Which is a lot of manipulations for the user (Enabling google dev account, requesting token to Google, generating a secret then pasting the token into the add-on). A good workaround is a custom advance filter related to video name as requested in #39 . In Tim Hunkin example video's a custom filter could match only all video with "The Secret Life of Components" in the title.
