### ISSUE TITLE
[Request] Like videos in the background 

### ISSUE THREAD

**Issue by leodoi3** [Taknok/youtube-auto-like#40]
Is it possible to automatically like videos even when the tab is not open? Like when a subscription or channel release a new video I want to automatically like that.

**Comment by Taknok** [comment]
This is possible, but not trough this add-on. This add-on inject JS on the youtube page. So by definition a youtube page need to be loaded in a browser. You can do this with [youtube API](https://developers.google.com/youtube) and basic python + cron (or if motivated a cleaner version with a server and a listener to youtube event).
