### ISSUE TITLE
Doesn't work before a live stream

### ISSUE THREAD

**Issue by leodoi3** [Taknok/youtube-auto-like#41]
**Expected Behavior**
It should automatically like

**Actual Behavior**
Nothing happens

**To Reproduce**
1. Go to a live stream that hasn't started yet

**Specification**
 - OS: Win 10
 - Browser version FF 87
 - Plugin version 3.2.4

**Comment by Taknok** [comment]
The like function is triggered only after the video has initiated to load. Thus, if live is not started yet, the video player has not loaded anything and like function is still pending. Unfortunately bypass the video loading would cause issue with angular async load and ad detection.
Thus, this is a "wanted behavior".

If anyone know how to do it, while still preserving ad detection and angular async, a PR is welcomed.
