### ISSUE TITLE
Allow list keeps changing to Block list mode

### ISSUE THREAD

**Issue by leodoi3** [Taknok/youtube-auto-like#42]
**Expected Behavior**
The options shouldnt change. 

**Actual Behavior**
There's this annoying bug where it keeps changing my option from Allow list to Block list mode. 

**To Reproduce**
1. It just happens by itself

**Specification**
 - OS: Win 10
 - Browser version FF 87
 - Plugin version 3.2.4

**Comment by Taknok** [comment]
Thank you for the report !
The change occurs randomly or right away ?

**Comment by leodoi3** [comment]
It happens randomly for me

**Comment by Taknok** [comment]
Is it still happening with the new version ?

**Comment by leodoi3** [comment]
So far nothing but it could happen anytime.

**Comment by Taknok** [comment]
Ok, pls keep me updated.

**Comment by runarsf** [comment]
Having the same issue, _Allow list mode_ automatically changes to _Block list mode_ as soon as I play a new video (v3.2.7).
Same goes for which videos to like, setting it to _Disable_ will automatically revert it to _Like only videos from subscribed creators_ as soon as a new video is started.

**Comment by Taknok** [comment]
Is the issue still present ? Do you have a Firefox account and does sync is enabled ? It seems to me that Firefox reset the settings of the addon.

**Comment by leodoi3** [comment]
I stopped using Firefox as I have switched to Brave. I haven’t noticed it lately before I switched but maybe other users have been having the same issue.
