### ISSUE TITLE
Only "use list" as whitelist works

### ISSUE THREAD

**Issue by NexusDarkshade** [Taknok/youtube-auto-like#43]
**Expected Behavior**
When not using whitelist or blacklist, the Like All, or Like from Subscribed Channels should still work

**Actual Behavior**
The auto-like functions only work when "use list" is enabled in whitelist mode

**To Reproduce**
1. Go to options
2. Select "use list" in whitelist mode and add channels to the list
3. View videos from those channels. 
4. Those videos will be liked.
5. Disable "use list" and view either subscribe channels if Like Subscribed is select or any other channel if Like All is selected.
6. Those videos will not be liked.

**Specification**
 - OS: Windows 10
 - Browser version: Firefox 87.0
 - Plugin version: 3.2.4

**Comment by Admiralmatt** [comment]
confirming i have the same issue. but i was able to get it to work with like all videos. Like only videos from subscribed channels does not work

**Comment by Taknok** [comment]
This is a issue with subscribed channel functionality, youtube change internal organization and add-on is lost in the new code.

**Comment by Taknok** [comment]
3.5.2 is sent to Firefox team. Tell me if issue is gone when the add-on is updated.

**Comment by NexusDarkshade** [comment]
It's working perfectly now. Thanks!
