### ISSUE TITLE
Issue in combination with YT Enhancer

### ISSUE THREAD

**Issue by DeadSix27** [Taknok/youtube-auto-like#5]
YT Enhancer on mozilla.org: https://addons.mozilla.org/en-US/firefox/addon/enhancer-for-youtube/

When using above AddOn with its "Player pinning" feature enabled (by setting: `Pin the video player at the bottom of the screen when scrolling down the page.(Firefox 53+)` to on),
your add-on keeps liking the video whenever it pins the video.

Presumably this is caused because YTE triggers a specific event again ?

Is it possible to store a variable like `alreadyLiked` per tab/session or so (I can't imagine it's not possible),

If so that would probably fix this issue.
  - Version: 2.0.4
  - Platform: FF 58.0b7 (old youtube style)

**Comment by Taknok** [comment]
Normally a checker named isRated does that, but maybe the YT Enhancer change the code and the function bugs. I will check that.

**Comment by DeadSix27** [comment]
@Taknok uh oh, seems like it actually just always likes the video every second, even with stylish and YT enhancer disabled, so vanilla youtube.

**Comment by Taknok** [comment]
I can't reproduce the issue...

**Comment by DeadSix27** [comment]
@Taknok I tested again and on FF 58.0b7 with all addons except auto liker disabled in a private window it still likes the video every second:
![image](https://user-images.githubusercontent.com/1492505/33479975-6c36a34c-d68f-11e7-9877-5a7b0c218ebe.png)

**Comment by Taknok** [comment]
I just tried on FF 58b7 without issue :(
Without YT Enhancer : 
![virtualbox_lubuntu-14-re350_29_11_2017_14_58_58](https://user-images.githubusercontent.com/12498020/33482876-6e41bf58-d69b-11e7-9e71-795264f6313b.png)

With : 
![virtualbox_windows_01_12_2017_13_27_24](https://user-images.githubusercontent.com/12498020/33482886-76dae34c-d69b-11e7-89d8-5e11c2513548.png)

What is your language setting ? And the settings on yt-auto-like ?

**Comment by DeadSix27** [comment]
@Taknok 
![image](https://user-images.githubusercontent.com/1492505/33482972-d563cd5c-d69b-11e7-9b2c-421262256616.png)
![image](https://user-images.githubusercontent.com/1492505/33483012-f82f705c-d69b-11e7-81f4-5853b827e68b.png)


I can check for tags if you want and run debug code, just need to tell me what.

**Comment by Taknok** [comment]
Try to put `console.log` before and after [this](https://github.com/Taknok/youtube-auto-like/blob/c187f881a809e2d6642e14e3dd0bee3786d59e23/app/scripts/modules/liker.js#L43) if block. What is the result ?

**Comment by DeadSix27** [comment]
@Taknok Is there any way to modify the addon code while running?

**Comment by Taknok** [comment]
You can clone this repo and import the addon with [about:debugging](about:debugging) or find the xpi package on the computer (I don't remember where) change the extension to .zip extract, modify, re-zip, rename .xpi. I suggest the debugging option ^^

**Comment by DeadSix27** [comment]
@Taknok Well I just used:
![image](https://user-images.githubusercontent.com/1492505/33483410-035f34c4-d69e-11e7-8685-b68a903e7e05.png)
After I modified a clone.

It's working now, so I assume the update procedure of firefox messed it up? That's the only thing I can think of, so you'd need to uninstall and reinstall it to get around that issue I guess.

Strange... did the setting-format change ?
Does the new version delete the old settings and add new ones? If not then maybe thats the issue?

**Comment by Taknok** [comment]
Normally not ... I will try to update from 2.0.3 to 2.0.4 to see if this is causing the issue.

**Comment by DeadSix27** [comment]
@Taknok Nvm, when I install the addon from the addonstore it bugs again.. weird

**Comment by Taknok** [comment]
O.o

**Comment by DeadSix27** [comment]
@Taknok Nvm-2, I guess I just had to clear the settings for the store-version addon. (I just forgot that a debug addon wouldnt have the same "addon-settings-storage" as the original. 

Now it works.. so ye it has something to do with the settings from the old version

**Comment by DeadSix27** [comment]
I wanna test if the version update causes this, how can I install an old version? (officially from the store)

**Comment by Taknok** [comment]
https://addons.mozilla.org/en/firefox/addon/youtube_auto_like/versions/

**Comment by DeadSix27** [comment]
@Taknok :) already found it ,see edit1-2, so it works fine and I really have no idea why it bugged in between versions like that... odd firefox hiccup?

**Comment by Taknok** [comment]
Ok, I reproduce the bug, it happens at upgrade from 2.0.3 to 2.0.4. Maybe the conf values from 2.0.3 are still present and mess with the new from 2.0.4 and firefox keep value from 2.0.3 untouchable. I will try quick stuff to fix it in 2.0.5...

**Comment by Taknok** [comment]
But anyway thank for the report and your perseverance :)

**Comment by DeadSix27** [comment]
@Taknok np, It's a handy addon, wouldn't want it gone.

**Comment by Taknok** [comment]
Does 2.0.5 fix the issue ?

**Comment by DeadSix27** [comment]
@Taknok I couldn't reproduce it :/ You said found out a way to reproduce it yourself though, didn't you?

**Comment by Taknok** [comment]
By installing 2.0.3 on a fresh firefox and upgrading to 2.0.4. But now 2.0.5 should fix it.
