### ISSUE TITLE
Appears to no longer function

### ISSUE THREAD

**Issue by JoelleEmmily** [Taknok/youtube-auto-like#50]
The Firefox add-on appears to no longer function. Attempted clearing whitelist, remove re-add, and like all setting; also switched between instant, timed, and random, likes are not applied in any mode or configuration. Bug seems to coincide with Firefox and Youtube update, though I'm not exactly sure which broke the add-on. I am also not certain that I have not changed a setting in Firefox that may be causing this issue.

**Comment by JoelleEmmily** [comment]
Has this bug been confirmed?

**Comment by Taknok** [comment]
Maybe related to #49

**Comment by MrGorsky** [comment]
It stopped working for me too, but I uninstalled the add-on, reinstalled it, and it worked again.

Windows 10 and Firefox fully updated.

**Comment by Marprog-jpg** [comment]
Same issue here, the add-on doesn't work even after reinstalling.

I am also on Windows 10 and on the latest version of Firefox.

**Comment by NexusDarkshade** [comment]
I have this issue as well, same as above two.

**Comment by Taknok** [comment]
Could you test this code in your youtube (with a video not liked) and send me the result (text written in console and if like is properly done )? `ctrl + shift + K` and past.
```js

// search the svg that has .style-scope.yt-icon (which is the svg used in yt-app)
function getActiveSVG() {
	var likeSvgRawList = document.querySelectorAll('g#like path');

	let svgs = null;
	let p = null;
	for (item of likeSvgRawList) {
		p = item.getAttribute("d");
		svgs = document.querySelectorAll(`path[d="${p}"]`);
		for (i of svgs) {
			if (i.matches(".style-scope.yt-icon")) return p;
		}
	}
	console.log("No active svg found.");
	return null;
}


var like = getActiveSVG();
var btn
var likeElement = document.querySelector(
	`ytd-video-primary-info-renderer #top-level-buttons-computed g.yt-icon path[d="${like}"], g.iron-icon path[d="${like}"]`
);
if (likeElement) {
	btn = likeElement.closest('yt-icon-button, paper-icon-button');
}
if (btn) {
	console.log("should be ok");
	btn.click();
} else {
	console.log("not ok");
}
```

**Comment by Marprog-jpg** [comment]
> 
> 
> Could you test this code in your youtube (with a video not liked) and send me the result (text written in console and if like is properly done )? `ctrl + shift + K` and past.
> 
> ```js
> // search the svg that has .style-scope.yt-icon (which is the svg used in yt-app)
> function getActiveSVG() {
> 	var likeSvgRawList = document.querySelectorAll('g#like path');
> 
> 	let svgs = null;
> 	let p = null;
> 	for (item of likeSvgRawList) {
> 		p = item.getAttribute("d");
> 		svgs = document.querySelectorAll(`path[d="${p}"]`);
> 		for (i of svgs) {
> 			if (i.matches(".style-scope.yt-icon")) return p;
> 		}
> 	}
> 	console.log("No active svg found.");
> 	return null;
> }
> 
> 
> var like = getActiveSVG();
> var btn
> var likeElement = document.querySelector(
> 	`ytd-video-primary-info-renderer #top-level-buttons-computed g.yt-icon path[d="${like}"], g.iron-icon path[d="${like}"]`
> );
> if (likeElement) {
> 	btn = likeElement.closest('yt-icon-button, paper-icon-button');
> }
> if (btn) {
> 	console.log("should be ok");
> 	btn.click();
> } else {
> 	console.log("not ok");
> }
> ```

It seems to work for me. I tested the code on a bunch of videos and they all got liked, along with "should be ok" being written in the console.

**Comment by JoelleEmmily** [comment]
Results in thumbs up being applied and "should be ok" in output

**Comment by GitMoleo** [comment]
> 
> 
> Results in thumbs up being applied and "should be ok" in output
> 
> "should be ok debugger eval code:27:10"

same here
