### ISSUE TITLE
Not working as of latest YouTube update

### ISSUE THREAD

**Issue by NexusDarkshade** [Taknok/youtube-auto-like#54]
Hello, the extension no longer seems to be working, now that YouTube has updated it's video layouts again. Even when "Like all videos" is selected, videos are not liked.

**Comment by Taknok** [comment]
Thank you for the report.
Unluckily I'm not selected in the A/B testing for the new layout. So I do not have access to the page.
Could you save me a page (`ctrl + s`) in HTML format and send me an archive here. With it I will be able to update de addon for this new layout.

**Comment by NexusDarkshade** [comment]
Here is the HTML zipped: [YouTube_Video.zip](https://github.com/Taknok/youtube-auto-like/files/7717237/YouTube_Video.zip)
Hopefully you won't have to scour too far to find the changes you need to make.

**Comment by Taknok** [comment]
There should also be a folder with the same name in the saved location (with JS and CSS). Could you send me this one too ?

![image](https://user-images.githubusercontent.com/12498020/146144810-d8b3e53d-ec89-4a9c-bd95-34d31354cd5b.png)

**Comment by NexusDarkshade** [comment]
I didn't see anything about JS or CSS files. I saved as "web page, complete" so shouldn't those be included?

**Comment by Taknok** [comment]
When you save a page on firefox to the desktop folder (for example), you should have the following structure:
```
download/
    | ... other files
    |
    | [name].htm
    | [name]_["file" at plural in firefox language defines in settings]
        | ... some stuffs here JS and CSS, folders etc
```
`[name]` is the selected name when saving the page.

`["file" at plural in firefox languages]` is the translated string.

Example with Firefox is in English and file is saved as `test`:
Could you send me `test.htm` & `test_files` ?

Example with Firefox is in French and file is saved as `demo`:
Could you send me `demo.htm` & `demo_fichiers` ?

Etc.

**Comment by NexusDarkshade** [comment]
[YouTube_Video (2).zip](https://github.com/Taknok/youtube-auto-like/files/7722172/YouTube_Video.2.zip)

**Comment by Taknok** [comment]
I just pushed a new version to GitHub. Could you download it and [install it as a temporary add-on](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension#installing) to test it ? (I cannot live test myself because I have not the new layout)
Download: https://github.com/Taknok/youtube-auto-like/archive/refs/heads/dev.zip

**Comment by Taknok** [comment]
When would you be able to test and send a feedback ?

**Comment by NexusDarkshade** [comment]
Hello, sorry I didn't reply. My computer was having issues with the GPU and I just only fixed them. The temporary add-on seems to be working. When I clicked on a video it was auto-liked.

**Comment by Taknok** [comment]
No problème, thank you ! Then, I publish the update on Firefox for everyone !

**Comment by Fraeksn** [comment]
FF 95.0.2 64-Bit
Plugin 3.4.0
For me it is not Working

**Comment by Taknok** [comment]
A revert version will be published shortly.

Can you send me the logs of the addons this will help me a lot to debug this ?
To activate the log :
1. click the addon logo to open the option popup window.
2. There do the [konami code](https://fr.m.wikipedia.org/wiki/Code_Konami)
3. Activate the debug option
4. Go to a youtube video which is not working
5. `ctrl+shift+k`
7. Copy the youtube auto like logs

And could you also send the YouTube page (`ctrl + s` and see above for the file & folder to send) ?

**Comment by Fraeksn** [comment]
[autolikeyoutube.zip](https://github.com/Taknok/youtube-auto-like/files/7750730/autolikeyoutube.zip)
where do i find the log in the inspector?

**Comment by Taknok** [comment]
Thank you for your reactivity !
 Sorry I was not clear. You need fisrt to activate the debugging in the addon :
1. Click the addon logo to open the option popup window.
2. There do the konami code
3. Activate the debug option

Once done you have to get the logs of the addon in this console:
https://developer.mozilla.org/en-US/docs/Tools/Browser_Console

I will release a short vidéo "how to".

**Comment by Fraeksn** [comment]
[console-export-2021-12-21_9-42-34.txt](https://github.com/Taknok/youtube-auto-like/files/7750847/console-export-2021-12-21_9-42-34.txt)
i hope this is correct :D

**Comment by Taknok** [comment]
@Fraeksn @NexusDarkshade
I just pushed a new version to GitHub. Could you download it and install it as a temporary add-on to test it both of you ?
Download: https://github.com/Taknok/youtube-auto-like/archive/refs/heads/dev.zip

**Comment by Fraeksn** [comment]
that one is working for me

**Comment by Taknok** [comment]
Firefox approved the hotfix, keep me updated if this 3.4.1 is working :)

**Comment by NexusDarkshade** [comment]
Hello, I didn't have time to check the hotfix before you pushed it, but the new version still works for me. I think it's safe to close the issue now.

**Comment by Taknok** [comment]
Thk for the feedback !
