### ISSUE TITLE
Compatibility with Return YouTube Dislike extension

### ISSUE THREAD

**Issue by Blagatt** [Taknok/youtube-auto-like#55]
**Expected Behavior**
Videos get automatically liked even when [Return YouTube Dislike](https://github.com/Anarios/return-youtube-dislike) is installed.

**Actual Behavior**
Videos don't get automatically liked when Return YouTube Dislike is installed.

**To Reproduce**
1. Install both extensions (YouTube Auto Like & Return YouTube Dislike)
2. Go to a video on YouTube that you know should be automatically liked
4. See that it doesn't get liked automatically :(

**Specification**
 - OS: Windows 10
 - Firefox 95.0.2 (64-bit)
 - YouTube Auto Like 3.4.1
 - Return YouTube Dislike 2.0.0.3

This feature might not be desired for this extension and I'd understand considering the other extension is causing the problem and that it might not work for very long (we'll see). At least this can serve as a way for other people in the same situation to understand what's happening.

**Comment by Taknok** [comment]
This is due to a lot of injected functions with the same name. JS does not know what is what anymore. I will see what can I do when I have free time.

**Comment by Taknok** [comment]
Both addons are working together on my Firefox... could you send me the logs of a video where it is not working ? https://www.youtube.com/watch?v=C4fQXRYwbrs&t=66s

**Comment by Blagatt** [comment]
I can confirm, the actual problem was detailed in #56 so I'm closing this issue.
