### ISSUE TITLE
Not working when the video is in fullscreen

### ISSUE THREAD

**Issue by Blagatt** [Taknok/youtube-auto-like#56]
**Expected Behavior**
Videos are automatically liked when a timer is set and video is watched in fullscreen.

**Actual Behavior**
Videos are not automatically liked when a timer is set and video is watched in fullscreen.

**To Reproduce**
1. Set a timer in the addon (whichever custom or random).
2. Watch the video until condition to be automatically liked is met.
3. See that it isn't liked :(

**Specification**
 - OS: Windows 10
 - Firefox 95.0.2 (64-bit)
 - YouTube Auto Like 3.4.1

The console reports 'No visible ActionsElements found. liker-material.js:51:6'.

**Comment by Taknok** [comment]
Can you send me the full log of the addon with the playlist and a video ? Here is how to : https://www.youtube.com/watch?v=C4fQXRYwbrs

**Comment by Blagatt** [comment]
Alright, I've done a bit more testing and it turns out it's not at all related to the Watch Later playlist (I'll let you adapt the title of the thread accordingly). The actual problem is when the video is viewed in fullscreen and thus using a timer to auto-like (whether fixed by minute, by percentage or even a random timer). The console reports 'No visible ActionsElements found. liker-material.js:51:6'.

[Here's a complete log](https://github.com/Taknok/youtube-auto-like/files/7789036/ytal_like-all_at60._fullscreen_fails.txt)

**Comment by Taknok** [comment]
I just pushed a new version to dev branch. Could you test it and tell me if the issue is fixed ?
 https://www.youtube.com/watch?v=C4fQXRYwbrs

**Comment by Blagatt** [comment]
Yup, looks like the fix works! Nice job :)
