### ISSUE TITLE
Unable to detect subscribed element

### ISSUE THREAD

**Issue by pauldesaintalbin** [Taknok/youtube-auto-like#63]
YouTube has released a new design, and now it doesn't work, undoubtedly because the structure of the "like" element has changed...
It was working until my account received the YouTube update.
Browser: Firefox Developer Edition 102
Addon version: 3.4.2

**Comment by Taknok** [comment]
There is different mode/timer to trigger the like: instant like, minute like, like % and random like.

**Comment by pauldesaintalbin** [comment]
I am using instant like.

**Comment by Taknok** [comment]
Ok, maybe you are in a region were they are testing a new youtube version, because the plugin is still working with the "new" version (2 month old for me). Could you send the log and the HTML source of youtube to allow me to replicate on my computer ?
Here is how to: https://www.youtube.com/watch?v=C4fQXRYwbrs&t=66s

**Comment by pauldesaintalbin** [comment]
So, like me, you are french, and when you type "you" in the search bar, the first link is a rickroll...
(laisse-moi un peu de temps pour faire la manip compliquée)

**Comment by NexusDarkshade** [comment]
> I am using instant like.

I'm also using instant like, and running into this issue.

Firefox Version: 101.0.1
Add-on Version: 3.4.2
Country: USA

**Comment by Fraeksn** [comment]
for me sub only like dont work. if i change to like all videos no problem.
FF: 101.0.1
Plugin: 3.4.2
[logs.zip](https://github.com/Taknok/youtube-auto-like/files/8929885/logs.zip)

**Comment by pauldesaintalbin** [comment]
> 

Same for me.

**Comment by Taknok** [comment]
@pauldesaintalbin are you using `all video` or `only subscribed` option ?

**Comment by Taknok** [comment]
I just pushed a (try of a) fix on the branch https://github.com/Taknok/youtube-auto-like/tree/63-unable-to-detect-subscribed-element can you tested it ? I have not the same youtube version with the issue on my computer so I cannot run proper live tests. The procedure is explained in the second part of the video, just download the correct branch and not the `dev` :)
Thank you for all the logs which were helpful.

**Comment by pauldesaintalbin** [comment]
It works! Thanks!

**Comment by Taknok** [comment]
Ok, I will send the new release to firefox and wait approbation.

**Comment by Taknok** [comment]
Is the issue still present with the version 3.5.0 ?

**Comment by NexusDarkshade** [comment]
Everything is working for me now.

**Comment by Taknok** [comment]
So I am assuming this issue is resolved and closed it. I will reopen it on request if needed.
