### ISSUE TITLE
Extention stopped working

### ISSUE THREAD

**Issue by iolqc** [Taknok/youtube-auto-like#66]
**Expected Behavior**
The extention is liking videos

**Actual Behavior**
Without changing anything, about 2 weeks ago, the extention stopped working using the setting : "like only video from subscribed channel", "Instant like", i tried % with no succes

**To Reproduce**
1. Using my computer, go to watch a video from subscribed channel 
2. See the video is never liked

**Specification**
 - OS: Windows 11 Home 10.0.22000 Build 22000
 - Browser version: Firefox 101.0.1 64-bit
 - Plugin version: 3.4.2
 - YouTube Premium: no
 - Youtube Player: normal
 - Youtube Country: Canada

**Comment by Taknok** [comment]
May be related to #63 , can you test the version 3.5.0 ?

**Comment by iolqc** [comment]
> May be related to #63 , can you test the version 3.5.0 ?

It working with 3.5.0 :)

Automatic updates were On, i thought i had latest version.

Automatic updates not firing?

**Comment by Taknok** [comment]
I send the 3.5.0 version to Firefox, they check there is no virus, update on store, then your Firefox check for update once every day. Generally all process is 2-3 days.

**Comment by Taknok** [comment]
I will close this issue and wait in 63 for confirmation :)
