### ISSUE TITLE
Plugin not working in new YouTube layout

### ISSUE THREAD

**Issue by NexusDarkshade** [Taknok/youtube-auto-like#68]
**Expected Behavior**
Like videos of subscribed channels instantly, according to the plugin settings.

**Actual Behavior**
Videos are not liked.

**To Reproduce**
1. Have the new YouTube layout.
2. Set plugin to instantly like subscribed channel's videos.
3. Go to a video of a subscribed channel.

**Screenshots**
![image](https://user-images.githubusercontent.com/43826341/187127462-137987c7-00ca-46c9-a6ec-295ed3359a2d.png)

**Logs**
[logs.zip](https://github.com/Taknok/youtube-auto-like/files/9441691/logs.zip)

**Specification**
 - OS: Windows 10
 - Browser version: Firefox 104
 - Plugin version: 3.5.0
 - YouTube Premium: no
 - Youtube Player: Any/All
 - Youtube Country: USA

**Comment by Taknok** [comment]
Thank you. I will look into this issue !

**Comment by Taknok** [comment]
Can you send a saved page of the video ? The page saved in the logs.zip seems to be the youtube home page.

**Comment by NexusDarkshade** [comment]
That's odd. I definitely saved the video.

**Comment by NexusDarkshade** [comment]
Yeah, I definitely saved the video page, but for some reason it keeps immediately redirecting back to the homepage whenever I open it.

**Comment by Taknok** [comment]
Ok, this is probably due to the new version. I will work on my side to bypass this redirection... Thk !

**Comment by AmidoNewsInside** [comment]
any news? ;--;

**Comment by Taknok** [comment]
Hi,
I just pushed a new version to the [dev branch](https://github.com/Taknok/youtube-auto-like/tree/dev). Could you tried it and tell me if it is working on the new paper version ?
How to: https://www.youtube.com/watch?v=C4fQXRYwbrs

**Comment by NexusDarkshade** [comment]
Success!
