### ISSUE TITLE
Addon not working

### ISSUE THREAD

**Issue by Dsingis** [Taknok/youtube-auto-like#69]
**Expected Behavior**
Addon should auto like creators I added to my list

**Actual Behavior**
It doesn't.

**To Reproduce**
1. Use Firefox
2. Install addon
3. Set to "like videos from subscribed channels"
4. Check "use list"
5. Set "allow mode"
6. Open video of subscribed creator (doesn't matter who)
7. Add creator to list
8. Reload video
9. Video doesn't get liked

**Screenshots**
![12363453412](https://user-images.githubusercontent.com/36317079/188869095-7639ef77-909a-4e55-89d0-be00077b8962.png)

**Log**

> blockMultipleRun: allow liker-material.js:412:7
> yt-autolike start liker-material.js:455:6
> options updated liker-material.js:27:6
> Get Video. liker-material.js:182:7
> No visible ActionsElements found. liker-material.js:41:7
> wait 1s for box liker-material.js:158:7
> blockMultipleRun: blocked liker-material.js:416:8
> ActionsElements found. 2 liker-material.js:57:7
> got buttons liker-material.js:124:7
> ActionsElements found. liker-material.js:57:7
> got buttons liker-material.js:124:7
> checking if video is rated liker-material.js:303:6

**Specification**
 - OS: Windows 10
 - Browser version: Firefox 104.0.1 
 - Plugin version: 3.5.0
 - YouTube Premium: no
 - Youtube Player: Theater
 - Youtube Country: Germany

**Comment by Taknok** [comment]
Related to #68 , I'm working on it :)

**Comment by Taknok** [comment]
Hi,
I just pushed a new version to the [dev branch](https://github.com/Taknok/youtube-auto-like/tree/dev). Could you tried it and tell me if it is working on the new paper version ?
How to: https://www.youtube.com/watch?v=C4fQXRYwbrs
