### ISSUE TITLE
Like Subscribed Channels likes all videos

### ISSUE THREAD

**Issue by NexusDarkshade** [Taknok/youtube-auto-like#74]
Not sure if this bug just started happening or if it's been here for a few versions, as I don't pay too much attention to whether I've liked a video and don't watch many videos from channels I'm not subscribed to.

**Expected Behavior**
Watching videos of unsubscribed channels while using "Like only videos from subscribed channels" shouldn't auto-like video.

**Actual Behavior**
The video is liked.

**To Reproduce**
1. Set to "Like only videos from subscribed channels" (no list) and "Instant Like"
2. Click on video from an unsubscribed channel
3. See error

**Logs**
[log.zip](https://github.com/Taknok/youtube-auto-like/files/10264155/log.zip)

**Specification**
 - OS: Windows 10
 - Browser version: Firefox 108.0.1
 - Plugin version: 3.6.1
 - YouTube Premium: no
 - Youtube Player: theater
 - Youtube Country: USA

**Comment by JinkerJinx** [comment]
I have the same issue with same specs.. tried reinstalling etc..  Will fiddling further/logging later.

**Comment by Taknok** [comment]
Hi, can on of you provide the logs of the addons in order to investigate the issue, please ?

**Comment by LittleVulpix** [comment]
@Taknok the logs attached in the original submission of the issue are not relevant? If so, please let me know how to take better/proper log and I can do it no problem. Thanks!

**Comment by Taknok** [comment]
My bad ... I check this right now!

**Comment by Taknok** [comment]
Can someone try the dev branch and tell me if the commit fix the issue ? [ttps://youtu.be/C4fQXRYwbrs](https://youtu.be/C4fQXRYwbrs)

**Comment by LittleVulpix** [comment]
I would love to try it but I have no idea how to "compile" or try an addon that isn't already in the xpi format...

**Comment by Taknok** [comment]
The video link in the comment describe how to :)

**Comment by LittleVulpix** [comment]
Aha, sorry. I see the video is a little outdated because the liker is now using "paper" isntead of "material" but I got it.
It no longer likes unsubscribed channels but it now also doesn't like the subscribed ones.

Here's a log from when I opened a new video from a subscribed channel:

```
blockMultipleRun: allow liker-paper.js:372:7
yt-autolike start liker-paper.js:415:6
options updated liker-paper.js:20:6
Get Video. liker-paper.js:155:7
ActionsElements found. 2 liker-paper.js:50:7
got buttons liker-paper.js:107:6
ActionsElements found. liker-paper.js:50:7
got buttons liker-paper.js:107:6
checking if video is rated liker-paper.js:276:6
is rated:  false liker-paper.js:280:7
Sub mode liker-paper.js:307:7
Use list: false liker-paper.js:314:6
Should like: false liker-paper.js:346:7
not liked check 1 liker-paper.js:430:9
```

**Comment by Taknok** [comment]
Thank you for the feedback ! Can you try it again with the new modifications ? Thank you !

**Comment by LittleVulpix** [comment]
Hi!
Yes, it worked now. I checked on some unsubbed channel and subbed channel and the results were per expectation. Just in case I'm also attaching the two logfiles from each channel.
[NOTSUBBED-console-export-2023-2-6_16-41-30.txt](https://github.com/Taknok/youtube-auto-like/files/10660740/NOTSUBBED-console-export-2023-2-6_16-41-30.txt)
[SUBBED-console-export-2023-2-6_16-43-15.txt](https://github.com/Taknok/youtube-auto-like/files/10660741/SUBBED-console-export-2023-2-6_16-43-15.txt)

**Comment by Taknok** [comment]
New version in review at firefox. Keep me updated if new bug related to this issue are found. Else it will be closed in 2 weeks :)

**Comment by JinkerJinx** [comment]
I installed 3.6.2.. everything seems fine now.. thank you!

**Comment by Taknok** [comment]
Ok, I am closing this issue since it seems fixed. Thank you for the contribution.
