### ISSUE TITLE
YouTube not supporting Autolike again

### ISSUE THREAD

**Issue by MykStreja** [Taknok/youtube-auto-like#78]
Using Firefox v110.0.1 Linux 21.0 Vanessa, on an HP Stream14. Set to Like All or Subscribed, no go. Gotta say, this is nice because I always forget to like after watching.

**Comment by Taknok** [comment]
Hi,

May be related to #59 

Can you activate the logs (guide https://youtu.be/C4fQXRYwbrs?t=68) and send it back here when you see the issue ? You just have to activate the log, use youtube normally, and when seeing the bug do ctrl + shift + K scroll to find the logs and paste here.

**Comment by Taknok** [comment]
Does the 3.6.3 solve this issue ?

**Comment by Taknok** [comment]
No answer. Seems to be resolved. Comment to re-open it.
