### ISSUE TITLE
Extensions Menu doesn't display custom setup

### ISSUE THREAD

**Issue by MerCrow** [Taknok/youtube-auto-like#8]
## Expected Behavior
Custom timer works properly.

## Actual Behavior
No way to set the custom timer (neither percentage nor minuters), no numbers appear in the field, clicks on the fields do nothing, neither do clicks on the up/down buttons.

## Steps to Reproduce the Problem

  1. Open 'Settings'
  2. Trying to set the custom timer up
  3. No way to do that (see Actual Behaviour)
![clip2net_171222184539](https://user-images.githubusercontent.com/34775670/34305887-02eaaf12-e749-11e7-870c-cfe4b68b43c0.png)
## Specifications

  - Version: 2.0.6
  - Platform: Firefox 56.0
  - Subsystem: Windows 8.1 Ent

**Comment by Taknok** [comment]
Hi, thank you for the report.
I suspect that you can't see the result because the box is too small, seems that the css rules didn't applies. To test it could you try to click in the box, then do `ctrl + a` to select all and type 0.017 (1s in min) and watch a video (subs or not depending of the other parameters) and see if it actually likes or not.

**Comment by MerCrow** [comment]
Hi,
Nope, it does nothing, I tried typing 0.017 and 1 after Ctrl+A - no autolike when watching.

I've just tried it on Windows 7 SP1, Firefox 57.0.2 - still both fields (minutes and %) are unclickable, and when you watch videos, it likes it instantly.

**Comment by Taknok** [comment]
Please could you give me your screen dimension and resolution.
If you download/clone the code from github, then go to `about:debugging` > load a temp module > select `manifest.json` in the folder *app*. Do you still have the bug ?

**Comment by MerCrow** [comment]
Got it! I tried to set it in Extensions section of Firefox as I usually do, not from the Tools panel:
![804b9-clip-8kb](https://user-images.githubusercontent.com/34775670/34323331-723e360e-e84d-11e7-8a86-9be4b1f27946.png)
In Tools panel, both fields work fine, but go unclickable in Extensions menu.

**Comment by Taknok** [comment]
Ok, I get it too. Modifications in `about:addons` aren't displayed, but they actually occur. I try to `ctrl + A` and type 12, then it show 12 in the tool panel. I will try to fix the extension menu for the next release. Thank for the report.

**Comment by Taknok** [comment]
So many time later (sorry) : https://github.com/Taknok/youtube-auto-like/commit/78a2b95b4b28b541f4a1e46cb4f36659c3b13358
