### ISSUE TITLE
Chrome .zip package

### ISSUE THREAD

**Issue by bremaya** [Taknok/youtube-auto-like#80]
Is it possible to create a .zip package with the Chrome extension to install in developer mode?  Thank you for working on this wonderful extension.

**Comment by Taknok** [comment]
You have to do some modifications as the `browser` element is named `chrome` on chrome. Probably some HTML element may differ too. The original extension was for chrome, but it was ban from the chrome store. There still is a .zip version : https://github.com/austencm/youtube-auto-like

**Comment by bremaya** [comment]
Thanks!
