### ISSUE TITLE
The "Add creator" button is not appearing at all and whitelist feature stopped working

### ISSUE THREAD

**Issue by Mikrowelliger** [Taknok/youtube-auto-like#81]
Don't remember exactly when it stopped working, maybe a few weeks ago? I tried reinstalling the addon today to see if that helped but all that did was empty my whitelist, oh well.

The only other addons I'm using are sponsorblock and youtube nonstop. This is my first time submitting an issue on github so I'll gladly help if you need any more information.

**Comment by Taknok** [comment]
Hi,

Thank you for reporting this issue.
You did well. I can confirm the issue on my side. Maybe for the next issue on github you can add the steps to reproduce (1. like go to this url etc) or the logs. But in this case you describe well enough. Thk
I will look into it asap.

**Comment by Taknok** [comment]
Hi,
Can you try the dev version and tell me if it solve the issue ? (Guide to install dev https://www.youtube.com/watch?v=C4fQXRYwbrs)

**Comment by alaestor** [comment]
I was also experiencing this and can confirm that the dev branch does fix it.  (tested liking % and all, adding/removing creators)

**Comment by Taknok** [comment]
New version sent to firefox. I will closed this issue in two weeks without activity.
