### ISSUE TITLE
ADD option to disable update popup tab

### ISSUE THREAD

**Issue by allanlaal** [Taknok/youtube-auto-like#83]
I love this plugin and recommend it to friends

however, at every update it opens up in a random firefox window out of ~100 in 36 workspaces in multiple parallel firefox versions on multiple machines

and by Murphys Law, it always covers up a very important single tab window that *needs* to keep running

**Comment by Taknok** [comment]
Thank for the suggestion.
Option added in 3.7.0. Comment to open if any issue is identified with the new feature. (Next update tab should be the last one if you opt out in option menu)
