### ISSUE TITLE
Bug: Extension likes every single video now

### ISSUE THREAD

**Issue by Gigafrost** [Taknok/youtube-auto-like#87]
**Expected Behavior**
The addon should only like videos from subbed channels

**Actual Behavior**
The addon likes any and every youtube video.

**To Reproduce**
1. Go to youtube.com
2. Click on any video
3. Watch as it likes the video whether you are subbed or not

**Specification**
 - OS: Win 11
 - Browser version: Firefox 119.0 (64-bit)
 - Plugin version: 3.8.0
 - YouTube Premium: No
 - Youtube Player: normal
 - Youtube Country: US

**Comment by Taknok** [comment]
Hi,

Thank you for your feedback ! I just tested in on my Firefox and it is working. Maybe you are in a region were they are testing a new youtube version. Could you send the log and the HTML source of youtube to allow me to replicate on my computer ?
Here is how to: https://www.youtube.com/watch?v=C4fQXRYwbrs&t=66s

**Comment by Nickwasused** [comment]
Hello, I've got the same problem on the following system:

- Firefox 115.4.0esr
- Windows 10
- Extension version 3.8.0
- Youtube in German

Extension settings are:
- only like subscribed channels
- with a custom time of 50% watched

All videos are liked after 50% of the video is watched.
  
[logs.zip](https://github.com/Taknok/youtube-auto-like/files/13197622/logs.zip)

**Comment by Taknok** [comment]
Hi,
I just pushed a new version to the [dev branch](https://github.com/Taknok/youtube-auto-like/tree/dev). Could you try it and tell me if it is working ?
How to: https://www.youtube.com/watch?v=C4fQXRYwbrs

**Comment by Nickwasused** [comment]
This is working for me 👍

**Comment by Taknok** [comment]
Update sent to Firefox and pending approval. You should receive the update within 48h. Feel free to re-open this issue if the problem persist with 3.8.1
