### ISSUE TITLE
Dose Not Work Anymore

### ISSUE THREAD

**Issue by SonGorLick** [Taknok/youtube-auto-like#90]
Expected Behavior
Auto-Likes Videos from Creators that i Subscribed to/Or Any Video.

Actual Behavior
It does nothing.
Changed Settings to "All Videos" and "Instant Like"/ect... still nothing

Specification

OS: Windows 10 (Version 22H2)
Browser version: Oprea Gx 105.0.4970.56
Plugin version: 3.8.1
YouTube Premium: no
Youtube Player: Theater/Normal
Youtube Country: USA

I think you may have to update the plugin since it isnt working at all

**Comment by Taknok** [comment]
Hi,

Thank you for your report. It is probably a new youtube layout html. Could you send the log and the HTML source of youtube to allow me to replicate on my computer ?
Here is how to: https://www.youtube.com/watch?v=C4fQXRYwbrs&t=66s

**Comment by SonGorLick** [comment]
Sadly, i tryed that and in Oprea Gx nothing happened when i typed what was shown in the video, nothing showed up

**Comment by Taknok** [comment]
Hi,
I didn't see that you have opera GX. Opera is based on chromium (the free part of chrome). It is normal that the Firefox version does not work. Try the chrome version : https://github.com/austencm/youtube-auto-like or https://gitlab.com/krishamade/youtubevideoliker

**Comment by SonGorLick** [comment]
Thanks, it worked, though its weird that this one was working fine for me before lol
