### ISSUE TITLE
Minute liker does not like when timer is longer than the video

### ISSUE THREAD

**Issue by Taknok** [Taknok/youtube-auto-like#92]
**Expected Behavior**
A video of 1 min with a timer of 2 min should be liked at 1 min.

**Actual Behavior**
The video is not liked.

**To Reproduce**
Need to be precised by @XangelMusic

**Screenshots**
Need to be precised by @XangelMusic

**Logs**
Need to be attached by @XangelMusic

**Specification**
 - OS: Windows 10
 - Browser version: Firefox 124.0.2
 - Plugin version: 3.8.2
 - YouTube Premium: no
 - YouTube Player: normal
 - YouTube Country: AU

**Comment by Taknok** [comment]
@XangelMusic could you please retry the instructions presented in this video to send the logs : https://www.youtube.com/watch?v=C4fQXRYwbrs&t=66s ? If the is no log at all it may be an error when injecting the script into the youtube page.

**Comment by XangelMusic** [comment]
@Taknok I just did a test with the latest version and it didn't work. This song is 4:04 minutes long and I had the timer at 10 minutes. This song didn't get liked when it finished and is still not Liked.

Console doesn't show anything with liker-material, but under liker-paper I do see a timer. The waitTimer just continuously keeps going at 244.838708 244.838708 10

[logs.zip](https://github.com/Taknok/youtube-auto-like/files/14926840/logs.zip)

**Comment by Taknok** [comment]
Yes sorry, the new youtube layout is paper, thus the logs appear on liker-paper.js.

Can you confirm this issue affect video and not live ?

**Comment by XangelMusic** [comment]
Yes, I can confirm this was on an actual video and not a live.

**Comment by Taknok** [comment]
3.9.1 should fix the issue, keep me updated.

**Comment by XangelMusic** [comment]
@Taknok Its working. Minute timer is on 10 minutes, and I watched a couple of music videos (which are less than 10 minutes) and they were liked once the songs were finished. 👍
